"""inicial_esquema_con_mejoras

Revision ID: 1c13ccfcaf55
Revises: 
Create Date: 2026-09-02 19:19:28.841049+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c13ccfcaf55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('entregado_por', sa.String(length=150), nullable=False),
    sa.Column('proyecto', sa.String(length=200), nullable=True),
    sa.Column('responsable_destino', sa.String(length=150), nullable=True),
    sa.Column('ciudad_destino', sa.String(length=100), nullable=True),
    sa.Column('direccion_destino', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('valor_aprox', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cajas', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actas_id'), 'actas', ['id'], unique=False)
    op.create_index(op.f('ix_actas_numero'), 'actas', ['numero'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_ubicaciones_id'), 'ubicaciones', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('valor_aprox', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.Column('foto', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipos_folio'), 'equipos', ['folio'], unique=True)
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_table('acta_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acta_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('dispositivo', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('detalle', sa.String(length=150), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['acta_id'], ['actas.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acta_items_id'), 'acta_items', ['id'], unique=False)
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('tecnico', sa.String(length=150), nullable=True),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_finalizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_id'), 'mantenimientos', ['id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('folio_acta', sa.String(length=50), nullable=True),
    sa.Column('persona', sa.String(length=150), nullable=True),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_mantenimientos_id'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    op.drop_index(op.f('ix_acta_items_id'), table_name='acta_items')
    op.drop_table('acta_items')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_folio'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_ubicaciones_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_actas_numero'), table_name='actas')
    op.drop_index(op.f('ix_actas_id'), table_name='actas')
    op.drop_table('actas')
    # ### end Alembic commands ###
