"""agregar tipo a activos

Revision ID: 5d4afa6ebe0c
Revises: 69637266c7ad
Create Date: 2026-09-21 14:40:37.379059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d4afa6ebe0c'
down_revision: Union[str, None] = '69637266c7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activos', sa.Column('tipo', sa.String(length=30), server_default='EQUIPO', nullable=False))
    op.create_index(op.f('ix_activos_tipo'), 'activos', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activos_tipo'), table_name='activos')
    op.drop_column('activos', 'tipo')
    # ### end Alembic commands ###