"""esquema inicial remaster

Revision ID: 69637266c7ad
Revises: 
Create Date: 2026-09-21 14:27:45.994457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

revision: str = '69637266c7ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=True),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('operacion_tipo', sa.String(length=40), nullable=True),
    sa.Column('operacion_id', sa.Integer(), nullable=True),
    sa.Column('ruta_pdf', sa.String(length=300), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actas_numero'), 'actas', ['numero'], unique=True)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('grupo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('estados_activo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('origen_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('destino_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('responsable_anterior_id', sa.Integer(), nullable=True),
    sa.Column('responsable_nuevo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('anulado_motivo', sa.String(length=255), nullable=True),
    sa.Column('anulado_usuario_id', sa.Integer(), nullable=True),
    sa.Column('anulado_fecha', sa.DateTime(), nullable=True),
    sa.Column('acta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimientos_activo_fecha', 'movimientos', ['activo_id', 'fecha'], unique=False)
    op.create_index('ix_movimientos_numero', 'movimientos', ['numero'], unique=True)
    op.create_index('ix_movimientos_tipo', 'movimientos', ['tipo'], unique=False)
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modulo', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_codigo'), 'permisos', ['codigo'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_codigo'), 'roles', ['codigo'], unique=True)
    op.create_table('tipos_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('archivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=40), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_entidad_id'), 'archivos', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_archivos_entidad_tipo'), 'archivos', ['entidad_tipo'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('accion', sa.String(length=30), nullable=False),
    sa.Column('modulo', sa.String(length=60), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.String(length=4000), nullable=True),
    sa.Column('valor_nuevo', sa.String(length=4000), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_entidad_id'), 'auditoria', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_auditoria_entidad_tipo'), 'auditoria', ['entidad_tipo'], unique=False)
    op.create_index(op.f('ix_auditoria_fecha'), 'auditoria', ['fecha'], unique=False)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria', ['usuario_id'], unique=False)
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('entidad_tipo', sa.String(length=40), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transiciones_estado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado_origen_id', sa.Integer(), nullable=False),
    sa.Column('estado_destino_id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('atributo_definiciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('requerido', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('contacto', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedores_nit'), 'proveedores', ['nit'], unique=False)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('ced_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedes_codigo'), 'sedes', ['codigo'], unique=True)
    op.create_table('responsables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsables_documento'), 'responsables', ['documento'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('solicitante', sa.String(length=150), nullable=True),
    sa.Column('categoria', sa.String(length=80), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_solucion', sa.DateTime(), nullable=True),
    sa.Column('solucion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_numero'), 'tickets', ['numero'], unique=True)
    op.create_table('ubicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('es_activa', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ubicaciones_sede_id'), 'ubicaciones', ['sede_id'], unique=False)
    op.create_table('acta_firmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acta_id', sa.Integer(), nullable=False),
    sa.Column('rol_firmante', sa.String(length=30), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('documento', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('ruta_firma', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('codigo_inventario', sa.String(length=50), nullable=True),
    sa.Column('placa', sa.String(length=50), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('qr_hash', sa.String(length=64), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('subcategoria_id', sa.Integer(), nullable=True),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_adquisicion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('factura_numero', sa.String(length=50), nullable=True),
    sa.Column('valor_adquisicion', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('garantia_meses', sa.Integer(), nullable=True),
    sa.Column('fecha_fin_garantia', sa.DateTime(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activos_codigo'), 'activos', ['codigo'], unique=True)
    op.create_index(op.f('ix_activos_codigo_inventario'), 'activos', ['codigo_inventario'], unique=False)
    op.create_index(op.f('ix_activos_estado_id'), 'activos', ['estado_id'], unique=False)
    op.create_index(op.f('ix_activos_placa'), 'activos', ['placa'], unique=False)
    op.create_index(op.f('ix_activos_qr_hash'), 'activos', ['qr_hash'], unique=True)
    op.create_index(op.f('ix_activos_responsable_id'), 'activos', ['responsable_id'], unique=False)
    op.create_index(op.f('ix_activos_serial'), 'activos', ['serial'], unique=False)
    op.create_index(op.f('ix_activos_ubicacion_id'), 'activos', ['ubicacion_id'], unique=False)
    op.create_table('activo_atributos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('atributo_definicion_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('motivo_tipo', sa.String(length=40), nullable=False),
    sa.Column('motivo_descripcion', sa.Text(), nullable=True),
    sa.Column('estado_fisico', sa.String(length=300), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bajas_numero'), 'bajas', ['numero'], unique=True)
    op.create_table('garantias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('fabricante', sa.String(length=150), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('documento', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garantias_activo_id'), 'garantias', ['activo_id'], unique=False)
    op.create_table('mantenimiento_programaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('periodicidad_meses', sa.Integer(), nullable=False),
    sa.Column('ultimo_ejecutado', sa.DateTime(), nullable=True),
    sa.Column('proxima_fecha', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('actividades', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=500), nullable=True),
    sa.Column('costo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('proxima_fecha', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mantenimientos_activo_id'), 'mantenimientos', ['activo_id'], unique=False)
    op.create_index(op.f('ix_mantenimientos_numero'), 'mantenimientos', ['numero'], unique=True)
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('fecha_prestamo', sa.DateTime(), nullable=True),
    sa.Column('fecha_prevista_devolucion', sa.DateTime(), nullable=True),
    sa.Column('fecha_devolucion_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prestamos_numero'), 'prestamos', ['numero'], unique=True)
    op.create_table('mantenimiento_repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mantenimiento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamo_accesorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('devuelto', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sysdiagrams')
    op.create_foreign_key('fk_responsables_sede_id', 'responsables', 'sedes', ['sede_id'], ['id'])
    op.create_foreign_key('fk_activos_marca_id', 'activos', 'marcas', ['marca_id'], ['id'])
    op.create_foreign_key('fk_activos_modelo_id', 'activos', 'modelos', ['modelo_id'], ['id'])
    op.create_foreign_key('fk_activos_categoria_id', 'activos', 'categorias', ['categoria_id'], ['id'])
    op.create_foreign_key('fk_activos_subcategoria_id', 'activos', 'subcategorias', ['subcategoria_id'], ['id'])
    op.create_foreign_key('fk_activos_estado_id', 'activos', 'estados_activo', ['estado_id'], ['id'])
    op.create_foreign_key('fk_activos_proveedor_id', 'activos', 'proveedores', ['proveedor_id'], ['id'])
    op.create_foreign_key('fk_activos_responsable_id', 'activos', 'responsables', ['responsable_id'], ['id'])
    op.create_foreign_key('fk_activos_ubicacion_id', 'activos', 'ubicaciones', ['ubicacion_id'], ['id'])
    op.create_foreign_key('fk_activos_creado_por', 'activos', 'usuarios', ['creado_por'], ['id'])
    op.create_foreign_key('fk_activo_atributos_activo_id', 'activo_atributos', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_activo_atributos_atributo_definicion_id', 'activo_atributos', 'atributo_definiciones', ['atributo_definicion_id'], ['id'])
    op.create_foreign_key('fk_subcategorias_categoria_id', 'subcategorias', 'categorias', ['categoria_id'], ['id'])
    op.create_foreign_key('fk_modelos_marca_id', 'modelos', 'marcas', ['marca_id'], ['id'])
    op.create_foreign_key('fk_proveedores_ciudad_id', 'proveedores', 'ciudades', ['ciudad_id'], ['id'])
    op.create_foreign_key('fk_transiciones_estado_estado_origen_id', 'transiciones_estado', 'estados_activo', ['estado_origen_id'], ['id'])
    op.create_foreign_key('fk_transiciones_estado_estado_destino_id', 'transiciones_estado', 'estados_activo', ['estado_destino_id'], ['id'])
    op.create_foreign_key('fk_atributo_definiciones_subcategoria_id', 'atributo_definiciones', 'subcategorias', ['subcategoria_id'], ['id'])
    op.create_foreign_key('fk_garantias_activo_id', 'garantias', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_garantias_proveedor_id', 'garantias', 'proveedores', ['proveedor_id'], ['id'])
    op.create_foreign_key('fk_bajas_activo_id', 'bajas', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_bajas_solicitante_id', 'bajas', 'responsables', ['solicitante_id'], ['id'])
    op.create_foreign_key('fk_bajas_aprobador_id', 'bajas', 'usuarios', ['aprobador_id'], ['id'])
    op.create_foreign_key('fk_bajas_usuario_id', 'bajas', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_bajas_acta_id', 'bajas', 'actas', ['acta_id'], ['id'])
    op.create_foreign_key('fk_actas_activo_id', 'actas', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_actas_movimiento_id', 'actas', 'movimientos', ['movimiento_id'], ['id'])
    op.create_foreign_key('fk_actas_usuario_id', 'actas', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_acta_firmas_acta_id', 'acta_firmas', 'actas', ['acta_id'], ['id'])
    op.create_foreign_key('fk_acta_firmas_responsable_id', 'acta_firmas', 'responsables', ['responsable_id'], ['id'])
    op.create_foreign_key('fk_archivos_usuario_id', 'archivos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_departamentos_pais_id', 'departamentos', 'paises', ['pais_id'], ['id'])
    op.create_foreign_key('fk_ciudades_departamento_id', 'ciudades', 'departamentos', ['departamento_id'], ['id'])
    op.create_foreign_key('fk_sedes_ciudad_id', 'sedes', 'ciudades', ['ciudad_id'], ['id'])
    op.create_foreign_key('fk_sedes_tipo_ubicacion_id', 'sedes', 'tipos_ubicacion', ['tipo_ubicacion_id'], ['id'])
    op.create_foreign_key('fk_sedes_ced_id', 'sedes', 'sedes', ['ced_id'], ['id'])
    op.create_foreign_key('fk_ubicaciones_sede_id', 'ubicaciones', 'sedes', ['sede_id'], ['id'])
    op.create_foreign_key('fk_ubicaciones_tipo_ubicacion_id', 'ubicaciones', 'tipos_ubicacion', ['tipo_ubicacion_id'], ['id'])
    op.create_foreign_key('fk_prestamos_activo_id', 'prestamos', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_prestamos_solicitante_id', 'prestamos', 'responsables', ['solicitante_id'], ['id'])
    op.create_foreign_key('fk_prestamos_responsable_id', 'prestamos', 'responsables', ['responsable_id'], ['id'])
    op.create_foreign_key('fk_prestamos_usuario_id', 'prestamos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_prestamos_acta_id', 'prestamos', 'actas', ['acta_id'], ['id'])
    op.create_foreign_key('fk_prestamo_accesorios_prestamo_id', 'prestamo_accesorios', 'prestamos', ['prestamo_id'], ['id'])
    op.create_foreign_key('fk_mantenimientos_activo_id', 'mantenimientos', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_mantenimientos_tecnico_id', 'mantenimientos', 'responsables', ['tecnico_id'], ['id'])
    op.create_foreign_key('fk_mantenimientos_proveedor_id', 'mantenimientos', 'proveedores', ['proveedor_id'], ['id'])
    op.create_foreign_key('fk_mantenimientos_usuario_id', 'mantenimientos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_mantenimientos_acta_id', 'mantenimientos', 'actas', ['acta_id'], ['id'])
    op.create_foreign_key('fk_mantenimiento_repuestos_mantenimiento_id', 'mantenimiento_repuestos', 'mantenimientos', ['mantenimiento_id'], ['id'])
    op.create_foreign_key('fk_mantenimiento_programaciones_activo_id', 'mantenimiento_programaciones', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_movimientos_activo_id', 'movimientos', 'activos', ['activo_id'], ['id'])
    op.create_foreign_key('fk_movimientos_origen_ubicacion_id', 'movimientos', 'ubicaciones', ['origen_ubicacion_id'], ['id'])
    op.create_foreign_key('fk_movimientos_destino_ubicacion_id', 'movimientos', 'ubicaciones', ['destino_ubicacion_id'], ['id'])
    op.create_foreign_key('fk_movimientos_responsable_anterior_id', 'movimientos', 'responsables', ['responsable_anterior_id'], ['id'])
    op.create_foreign_key('fk_movimientos_responsable_nuevo_id', 'movimientos', 'responsables', ['responsable_nuevo_id'], ['id'])
    op.create_foreign_key('fk_movimientos_usuario_id', 'movimientos', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_movimientos_anulado_usuario_id', 'movimientos', 'usuarios', ['anulado_usuario_id'], ['id'])
    op.create_foreign_key('fk_movimientos_acta_id', 'movimientos', 'actas', ['acta_id'], ['id'])
    op.create_foreign_key('fk_notificaciones_usuario_destino_id', 'notificaciones', 'usuarios', ['usuario_destino_id'], ['id'])
    op.create_foreign_key('fk_tickets_sede_id', 'tickets', 'sedes', ['sede_id'], ['id'])
    op.create_foreign_key('fk_tickets_tecnico_id', 'tickets', 'usuarios', ['tecnico_id'], ['id'])
    op.create_foreign_key('fk_usuario_roles_usuario_id', 'usuario_roles', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key('fk_usuario_roles_rol_id', 'usuario_roles', 'roles', ['rol_id'], ['id'])
    op.create_foreign_key('fk_rol_permisos_rol_id', 'rol_permisos', 'roles', ['rol_id'], ['id'])
    op.create_foreign_key('fk_rol_permisos_permiso_id', 'rol_permisos', 'permisos', ['permiso_id'], ['id'])
    op.create_foreign_key('fk_auditoria_usuario_id', 'auditoria', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61D54F0A92'))
    )
    op.drop_table('prestamo_accesorios')
    op.drop_table('mantenimiento_repuestos')
    op.drop_index(op.f('ix_prestamos_numero'), table_name='prestamos')
    op.drop_table('prestamos')
    op.drop_index(op.f('ix_mantenimientos_numero'), table_name='mantenimientos')
    op.drop_index(op.f('ix_mantenimientos_activo_id'), table_name='mantenimientos')
    op.drop_table('mantenimientos')
    op.drop_table('mantenimiento_programaciones')
    op.drop_index(op.f('ix_garantias_activo_id'), table_name='garantias')
    op.drop_table('garantias')
    op.drop_index(op.f('ix_bajas_numero'), table_name='bajas')
    op.drop_table('bajas')
    op.drop_table('activo_atributos')
    op.drop_index(op.f('ix_activos_ubicacion_id'), table_name='activos')
    op.drop_index(op.f('ix_activos_serial'), table_name='activos')
    op.drop_index(op.f('ix_activos_responsable_id'), table_name='activos')
    op.drop_index(op.f('ix_activos_qr_hash'), table_name='activos')
    op.drop_index(op.f('ix_activos_placa'), table_name='activos')
    op.drop_index(op.f('ix_activos_estado_id'), table_name='activos')
    op.drop_index(op.f('ix_activos_codigo_inventario'), table_name='activos')
    op.drop_index(op.f('ix_activos_codigo'), table_name='activos')
    op.drop_table('activos')
    op.drop_table('acta_firmas')
    op.drop_index(op.f('ix_ubicaciones_sede_id'), table_name='ubicaciones')
    op.drop_table('ubicaciones')
    op.drop_index(op.f('ix_tickets_numero'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_responsables_documento'), table_name='responsables')
    op.drop_table('responsables')
    op.drop_index(op.f('ix_sedes_codigo'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_proveedores_nit'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_table('ciudades')
    op.drop_table('atributo_definiciones')
    op.drop_table('usuario_roles')
    op.drop_table('transiciones_estado')
    op.drop_table('subcategorias')
    op.drop_table('rol_permisos')
    op.drop_table('notificaciones')
    op.drop_table('modelos')
    op.drop_table('departamentos')
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_fecha'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidad_tipo'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidad_id'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_archivos_entidad_tipo'), table_name='archivos')
    op.drop_index(op.f('ix_archivos_entidad_id'), table_name='archivos')
    op.drop_table('archivos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_ubicacion')
    op.drop_index(op.f('ix_roles_codigo'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_codigo'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_table('paises')
    op.drop_index('ix_movimientos_tipo', table_name='movimientos')
    op.drop_index('ix_movimientos_numero', table_name='movimientos')
    op.drop_index('ix_movimientos_activo_fecha', table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_table('marcas')
    op.drop_table('estados_activo')
    op.drop_table('configuracion')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_actas_numero'), table_name='actas')
    op.drop_table('actas')
    # ### end Alembic commands ###