"""add foto piezas a mantenimientos

Revision ID: 79a1f85d82fd
Revises: 1c13ccfcaf55
Create Date: 2026-09-03 12:56:30.154296+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a1f85d82fd'
down_revision = '1c13ccfcaf55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mantenimientos', sa.Column('foto', sa.String(length=300), nullable=True))
    op.add_column('mantenimientos', sa.Column('piezas', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mantenimientos', 'piezas')
    op.drop_column('mantenimientos', 'foto')
    # ### end Alembic commands ###
